name: Deploy to Hostinger

on:
  push:
    branches:
      - dist   # Solo se ejecuta cuando hay cambios en la rama dist

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hostinger Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            https://webhooks.hostinger.com/deploy/da9e4d374c9bdf92f5fffe4c434ddc8a
