name: Deploy to Hostinger on dist push

on:
  push:
    branches:
      - dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Check if workflow runs
        run: echo "✅ Workflow triggered by push to dist branch"

      - name: Trigger Hostinger Webhook
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://webhooks.hostinger.com/deploy/da9e4d374c9bdf92f5fffe4c434ddc8a")
          
          # Separa el cuerpo de la respuesta y el código de estado HTTP
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | sed '$d')
          
          echo "Response HTTP Code: $http_code"
          echo "Response Body: $response_body"
          
          if [[ "$http_code" -ge 200 && "$http_code" -lt 300 ]]; then
            echo "✅ Webhook triggered successfully!"
          else
            echo "❌ Webhook failed with HTTP code $http_code"
            echo "Response: $response_body"
            exit 1 # Falla el step si el código de estado no es 2xx
          fi
