name: Build Astro and Deploy to Hostinger

on:
  push:
    branches:
      - main   # Se ejecuta cada vez que haces push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install dependencies
        run: npm install

      - name: Build Astro
        run: npm run build

      - name: Push to dist branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy $(date)"
          git branch -M dist
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin dist

      - name: Deploy via SFTP to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}     
          username: ${{ secrets.HOSTINGER_USER }}  
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002                                # puerto SSH/SFTP que te dio Hostinger
          source: "./dist/*"                         # carpeta generada por Astro
          target: "/public_html/"                    # carpeta en el servidor
